### ISSUE TITLE
Support search by table and column descriptions

### ISSUE THREAD

**Issue by abhishenator** [lyft/amundsen#150]
Hello,

I would imagine that search on text(descriptions, etc) is the most basic thing that would be supported by Amudsen as it uses Elasticsearch. Though I don't see this simple search functionality being supported currently(at least not clear from documentation and high-level glimpse at the code). Amudsen could have used a key-value store or SQL DB to store the metadata if it is not supporting simple text search via Elasticsearch.

This feature will be very valuable for discovery.

Thanks

**Comment by abhishenator** [comment]
Looks like this is supported. Though, when I edit description from UI, that description does not become effective for search.

**Comment by feng-tao** [comment]
It is supported, but it depends on when the search index/document is built.

**Comment by abhishenator** [comment]
Thanks Feng! Does the index rebuild happen automatically?

**Comment by jornh** [comment]
@abhishenator is does not happen automatically - yet!

Updates (from the front-end UI) of `Description`, `Tag`, and now that I think of it also `Owner` fields only update the metadata, but not the search service.

So this issue is essentially just a variation of #52 with the same fix with re-running the ES update job as mentioned in https://github.com/lyft/amundsen/issues/52#issuecomment-500339360.

For `Tags` there's actually already a PR https://github.com/lyft/amundsenmetadatalibrary/pull/76 
... @feng-tao any way the community can help towards getting that merged? 
Adding handling of `Owner` and `Comment` fields on top of that PR should be a `good first issue` to start with the Amundsen codebase. (😉 hint-hint)

**Comment by feng-tao** [comment]
I think calling search from metadata would not be a prefer way. We could do it in FE side .
