### ISSUE TITLE
fetch_table_search_results_with_field fails for empty string

### ISSUE THREAD

**Issue by sandeshvijayraj** [lyft/amundsen#243]
fetch_table_search_results_with_field function of elasticsearch.py in amundsen search fails BCS it doesn't have a test for empty string as fetch_table_search_results has can this be implemented to avoid an error.

**Comment by jornh** [comment]
@sandeshvijayraj please take a look at the PR https://github.com/lyft/amundsensearchlibrary/pull/90#issuecomment-603096057 - maybe even take it for a test drive.

Thanks!

**Comment by feng-tao** [comment]
the pr is merged, @sandeshvijayraj could you try again?

**Comment by ttannis** [comment]
The PR in question didn't update `fetch_table_search_results_with_field` though, it updated logic used in `fetch_table_search_results_with_filter`. That being said because we intend to deprecate `fetch_table_search_results_with_field` for `fetch_table_search_results_with_filter`, I think this issue can still be closed.

**Comment by feng-tao** [comment]
yeah
