### ISSUE TITLE
amundsenfrontend    |   File "/usr/local/lib/python3.7/site-packages/amundsen_frontend-1.0.6-py3.7.egg/amundsen_application/api/metadata/v0.py", line 471, in update_bookmark amundsenfrontend    |     raise Exception('AUTH_USER_METHOD is not configured')

### ISSUE THREAD

**Issue by satishjb** [lyft/amundsen#27]
I am running docker version of amundsen. I can see search page with sample table however when i drill down table profile show always loading and I get this error.

amundsenfrontend    |   File "/usr/local/lib/python3.7/site-packages/amundsen_frontend-1.0.6-py3.7.egg/amundsen_application/api/metadata/v0.py", line 471, in update_bookmark
amundsenfrontend    |     raise Exception('AUTH_USER_METHOD is not configured')

Firebug

v0/ 

says {"msg":"A client for the preview feature must be configured","previewData":{}}

auth_user

{"msg":"Encountered exception: AUTH_USER_METHOD is not configured"}

What could be the issue
![Amun](https://user-images.githubusercontent.com/51740866/62287005-8f9bbe00-b476-11e9-8f8b-7aae28d917bf.png)

**Comment by jornh** [comment]
The "Quickstart" docker version currently doesn't include any configuration for authentication. 

The `Loading ...` indicator you see is an unrelated fronted UI bug. It has been fixed in master (original issue https://github.com/lyft/amundsenfrontendlibrary/issues/202) but no new release of that container has been released since.

Regarding auth, the error message says it pretty clearly: `AUTH_USER_METHOD is not configured`. Currently I think it's still early days regarding setting up something like this.

If you're up to tinkering with configuring it then see the currently available documentation offering _one_ option for setting up auth: https://github.com/lyft/amundsenfrontendlibrary/blob/master/docs/configuration.md#authentication

There is an open issue https://github.com/lyft/amundsenfrontendlibrary/issues/212  to improve deployment docs - including auth setup - and contributions/experiences/documentation in this area are more than welcome. The more people able to contribute the faster Amundsen can mature in this area as well.

**Comment by satishjb** [comment]
Thank you for responding. I understand that this project needs contribution I will be glad once I get a hang of the system and local setup running.

As you mentioned regarding the docker, is there a docker file that we can build with the latest code changes from master.

Does Auth not available in docker mean that its possible in local setup.

**Comment by jornh** [comment]
Cool that you already got a successful frontend build done, and you could get rid of that confusing UI glitch. That’s also what we’re hoping for to quickly onboard people.

For the foreseeable future I don’t think the “data preview” view will be part of a out-of-box install for neither “Quickstart” nor a production deployment without any config. The reason is it’s actually built as an optional integration requiring some additional configuration. It relies on a REST call to an external BI tool you must also install and connect to you data sources separately (currently supporting Apache SuperSet) to serve the tabular preview data.

If you are particularly interested in that feature the guide to configure it is here: https://github.com/lyft/amundsenfrontendlibrary/blob/master/docs/examples/superset_preview_client.md

I hope this clears the immediate issue for you. I will recommend the Slack chat where a lot of discussion around use and future ideas - also of “data preview” recently - already has happened.
