### ISSUE TITLE
Searching on multiple fields doesn't return results. 

### ISSUE THREAD

**Issue by lukelowery** [lyft/amundsen#315]
For example, if I search for `table:test_table schema:test_schema` I expect to get test_schema.test_table, but I don't get anything. 

`table:test_table test_schema` Work fine.

**Comment by feng-tao** [comment]
@lukelowery we just check in a change to allow search filter which should serve your need. Currently waiting for the FE change to merge. cc @ttannis

**Comment by ttannis** [comment]
For more context @lukelowery
1. The initial advanced search syntax support only supports one field
2. The new filter support work will allow you to filter across multiple fields in the UI vs. typing in the syntax. 

Closing this issue since the behavior you see was actually how that was written to work, and the upcoming improvements will make that kind of search possible.
