### ISSUE TITLE
Databuilder do not sync when columns removed

### ISSUE THREAD

**Issue by devlucasc** [lyft/amundsen#370]
Databuilder do not sync when columns removed, is needed to delete when column do not exists in extractor but still exists in neo4j database

**Comment by jornh** [comment]
@devlucasc I think https://github.com/lyft/amundsendatabuilder/blob/master/databuilder/task/neo4j_staleness_removal_task.py might be what you're looking for. There's currently no real documentation for it - but you can find a few mentions of it and explanation of it's intended use in the Amundsen Slack channel. 

If this helps you please consider contributing the documentation that you see missing so it doesn't get lost eventually due to limited Slack history. Thanks!

**Comment by jornh** [comment]
Uhm, wait - just looked at the PR where it was added: https://github.com/lyft/amundsendatabuilder/pull/235 

There *is* already documentation: 
https://github.com/lyft/amundsendatabuilder#removing-stale-data-in-neo4j----neo4jstalenessremovaltask

So maybe it's more a matter of _findability_ ... contributions are **_very_** welcome as to improve the situation. As a first step "what do you think would have helped to find the needed info?"

**Comment by devlucasc** [comment]
Hi @jornh, thanks a lot, this feature will help me. Sorry for boring you, when I searched, I was looking for issues with keyword "delete". I need to pay more attention.

**Comment by jornh** [comment]
No worries 😉 I which you better google-fu next time ...
