### ISSUE TITLE
Unable to Integrate Preview Client with Superset

### ISSUE THREAD

**Issue by ayushbilala** [lyft/amundsen#386]
Hi,
I am looking to make use of Amundsen's data preview feature with Superset using sql_json endpoint.
I am getting an exception 'CSRF token is missing', even though it is there in the request (screenshot atttached).
Can someone please let me know the right way to query sql_json endPoint with CSRF token?
PS: I played with below configurations as well, but nothing helped.
```
WTF_CSRF_EXEMPT_LIST = ['superset.views.core.sql_json']
# WTF_CSRF_ENABLED = True
SESSION_COOKIE_SAMESITE = None
SESSION_COOKIE_HTTPONLY = False

```
![image](https://user-images.githubusercontent.com/6296026/79509621-7ca73900-8059-11ea-8609-f21c190fd4ab.png)
CC: @ttannis @feng-tao

**Comment by feng-tao** [comment]
cc @betodealmeida @khtruong @john-bodley 
Hey Beto, Kim, John, @ayushbilala is a member in Amundsen OSS community . He tried to setup the connection between Amundsen and Superset to do data preview and got that error. Do you happen to know how to fix the csrf token missing issue?

I looked at Lyft superset config which doesn't get much clue as we also just put that sql_json endpoint in the WTF_CSRF_EXEMPT_LIST.

also cc @ttannis

**Comment by khtruong** [comment]
Hi @ayushbilala, can you share the exact file path where you are saving your Superset settings?

**Comment by ayushbilala** [comment]
@khtruong it is within a docker container. /app/pythonpath/superset_config.py

**Comment by ayushbilala** [comment]
@khtruong I managed to go past the CSRF exception by supplying CSRF token in request header. But facing another error now. (screenshot attached)

![image](https://user-images.githubusercontent.com/6296026/79515624-c2b6c980-8066-11ea-8328-856c9f48f9d2.png)

**Comment by feng-tao** [comment]
@ayushbilala the error seems to be specific to superset. I would suggest just to follow up with superset oss slack channel as @ttannis mentioned that Lyft superset may not be the same as the one you used.

**Comment by ayushbilala** [comment]
Yes agreed.

**Comment by feng-tao** [comment]
@ayushbilala I add a tutorial(https://lyft.github.io/amundsen/tutorials/data-preview-with-superset/) . Feel free to reopen if it doesn't work.

**Comment by pranavsethi** [comment]
@feng-tao  .. 
Thanks for great contribution on Lyft

We are trying to integrate the Superset-Snowflake preview feature with Lyft .
Currently the flow is such :
- Superset hosted in a Docker - Running on 8088
- Amundsen Frontend hosted on 5000 using amundsen on Docker 

Both Docker Networks connected to each other , thus the API is reachable from inside Frontend Docker using :
curl http://superset_app:8088/superset/sql_json/
(superset_app is container name)

We are using the example_superset_preview_client.py and replaced the

 DEFAULT_URL = 'http://superset_app:8088/superset/sql_json/'
 
We get the "Method Not Allowed" Error while hitting the API from inside the container.

I suspect this issue to be login issue from Superset . Can you help ,what needs to be added in the example_superset_preview_client.py for authentication so that it can get the data ?

**Comment by feng-tao** [comment]
@pranavsethi I would suggest to follow with superset slack channel as different version has different endpoint security setting.

**Comment by marshell0** [comment]
This issue is related to authentication.
for @ayushbilala's issue, you could obtain csrf_token token from the home page response, then use it in your login like this:
login_data = {'username': 'user', 'password': 'pass', 'provider': 'ldap', 'refresh': True, 'csrf_token': csrf_token}
session.post(url=login_url, data=login_data)
Then following the steps in Amundsen, you can get the right response.
