### ISSUE TITLE
favourite button in frontend not working

### ISSUE THREAD

**Issue by siddharthgarishakurthi** [lyft/amundsen#82]
Even after clicking on the favorite option , i am unable to store it as favorite table.

**Comment by jornh** [comment]
You need to have user authentication enabled for this to work. It could get clarified by documentation (see some proposed draft WIP in https://github.com/lyft/amundsen/issues/53)

**Comment by ttannis** [comment]
@siddharthgarishakurthi second to what @jornh said, I think it is likely that the feature is not configured correctly, therefore the request fails, and therefore the UI does not update. When you open your network tab in the browser and click the favorite button, are you getting an error?

**Comment by jornh** [comment]
@siddharthgarishakurthi did you get this working or not?

As it stands I don't see any actionable info for the. If you still think there's an issue please provide additional info (e.g. steps to reproduce) so we someone can try to help resolve it.

**Comment by siddharthgarishakurthi** [comment]
@jornh it is not working for me

Can you please share how to enable the user authentication if possible as i could not understand the doc provided in this link : https://github.com/lyft/amundsen/blob/master/docs/authentication/oidc.md

Sorry for late reply .. I was busy with some other projects.

**Comment by jornh** [comment]
No worries. OK, got it, so as I understand it the issue is more like:
> “when trying to set up auth using the OIDC guide - how do I verify/troubleshoot that I configured each step correctly”?

Personally I haven’t gotten to try setting up OIDC. So I can’t give you a direct answer. I have merely set up one hardcoded userid to try out all the user profile stuff. 

What I do know is that ING has it working in their setup (they built it) - and so far I know of _one_ thread on Slack that sadly died, til now: https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1567144954013700?thread_ts=1567121193.012100&channel=CGFBVT23V&message_ts=1567144954.013700

How far have you gotten compared to that thread? - can you describe steps you took and results/error messages you got - or specific questions you have? If you can do that I’m sure we can collective get to a better situation.

**Comment by feng-tao** [comment]
you mean bookmark button(the star shape)? CC @ttannis @danwom

**Comment by danwom** [comment]
@feng-tao The bookmark/favorite/follow star is not hidden by any config at the moment. At minimum the bookmark feature requires authentication the bookmarks can be linked to the user. (This does not require the `indexUsers` feature to be enabled). There is an implicit assumption that authentication will be used, but perhaps some instances won't have it (maybe just hide the site behind a VPN?). In those cases we could consider hiding the bookmarks behind a feature flag.

**Comment by jornh** [comment]
@siddharthgarishakurthi I made a super-simple fix to the issue you originally posted in https://github.com/lyft/amundsen/issues/82#issue-480579885 above. 

Please do a `git pull` of this repo - and see if it works for you for at least demoing with the Quickstart setup. (Then we're at least _one_ although _tiny_ step towards an improved Amundsen unboxing experirence).

**Comment by siddharthgarishakurthi** [comment]
@jornh thank you for the changes .. The favourite button is working now and i am able to see the My bookmarks section in frontend.

**Comment by feng-tao** [comment]
thanks @siddharthgarishakurthi and @jornh
